# Generated by Django 2.0.5 on 2018-05-18 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoesWellWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('allergy', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Menu items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablenumber', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Menu')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Order')),
            ],
            options={
                'verbose_name_plural': 'Order lines',
            },
        ),
        migrations.AddField(
            model_name='goeswellwith',
            name='menuitem1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Primary item+', to='API.Menu'),
        ),
        migrations.AddField(
            model_name='goeswellwith',
            name='menuitem2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Second item+', to='API.Menu'),
        ),
    ]
